# Generated by Django 4.1.5 on 2023-02-02 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='N0togri',
            new_name='Notogri',
        ),
    ]
